### ISSUE TITLE
Help! gspread can't find spreadsheet 

### ISSUE THREAD

**Issue by drhisham-code** [paramt/Q4T#4]
``` 
 python src/main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.0/x64
/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/x509.py:15: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/gspread/client.py", line 121, in open
    properties = finditem(
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/gspread/utils.py", line 47, in finditem
    return next((item for item in seq if func(item)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/FRCA-Qbot/FRCA-Qbot/src/main.py", line 19, in <module>
    datasheet = gc.open(config.spreadsheet).worksheet("datasheet")
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/gspread/client.py", line 131, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound
Error: Process completed with exit code 1.
```

gspread can't find spreadsheet , however my API endpoint is registering 200 OK, I have checked the name/title of the spreadsheet, or is it based on id ?

**Comment by drhisham-code** [comment]
```
You will automatically download a JSON file with credentials. It may look like this:

{
    "type": "service_account",
    "project_id": "api-project-XXX",
    "private_key_id": "2cd … ba4",
    "private_key": "-----BEGIN PRIVATE KEY-----\nNrDyLw … jINQh/9\n-----END PRIVATE KEY-----\n",
    "client_email": "473000000000-yoursisdifferent@developer.gserviceaccount.com",
    "client_id": "473 … hd.apps.googleusercontent.com",
    ...
}
Remember the path to the downloaded credentials file. Also, in the next step you’ll need the value of client_email from this file.

Very important! Go to your spreadsheet and share it with a client_email from the step above. Just like you do with any other Google account. If you don’t do this, you’ll get a gspread.exceptions.SpreadsheetNotFound exception when trying to access this spreadsheet from your application or a script.

```

digging through gspred docs i found the solution , should be added to read me
